<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedStoreAPI.Domain\MedStoreAPI.Domain.csproj" />
    <ProjectReference Include="..\MedStoreAPI.Entities\MedStoreAPI.Entities.csproj" />
    <ProjectReference Include="..\MedStoreAPI.Dtos\MedStoreAPI.Dtos.csproj" />
    <ProjectReference Include="..\MedStoreAPI.Common\MedStoreAPI.Common.csproj" />
  </ItemGroup>

</Project>
